s = int(input("Enter sid of student: "))
n = input("Enter name of student: ")
g = input("Enter gender of student: ")
t = input("Enter course name of student: ")
c = int(input("Enter cgpa of student: "))
print("Name:", n, "sid:", s, "gender:", g, "course name:" ,t, "cgpa:",c)
print()
print()
print("sid:", s)
print("Name:", n)
print("gender:", g)
print("course name:", t)
print("cgpa:", c)